# Generated by Django 4.2.3 on 2023-07-08 10:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=60, verbose_name="Name of the company"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="E-mail address of the company"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Text description of the company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, verbose_name="Full name of the employee"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="E-mail address of the employee"
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        default=18,
                        validators=[django.core.validators.MinValueValidator(18)],
                        verbose_name="Age of the employee, must be at least 18",
                    ),
                ),
                (
                    "jobTitle",
                    models.CharField(
                        choices=[
                            ("accountant", "Accountant"),
                            ("software developer", "Software Developer"),
                            ("software tester", "Software Tester"),
                            ("manager", "Manager"),
                        ],
                        max_length=20,
                        verbose_name="Job title of the employee",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="api.company",
                        verbose_name="Place of employment of the employee",
                    ),
                ),
            ],
        ),
    ]
